

parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: ukmdelta_db
    database_user: ukmdev_devwrite
    database_password: devonly
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    debug_toolbar: true
    debug_redirects: false
    use_assetic_controller: true
    ukmsms.system_id: UKMdelta
    ukmsms.price: 0.4
    ukmsms.sender: UKMNorge
    ukmdelta.sms.validation.text: '#code er din engangskode for å opprette UKM-bruker.'
    ukmdelta.sms.password.reset_text: 'Trykk på lenken for å resette ditt passord. #link'
    ukmdelta.sms.password.created: 'Din UKM-bruker er opprettet! Neste gang du skal logge inn, bruker du passordet #code'
    facebook_client_id: Facebook-App-ID-dev
    facebook_client_secret: Facebook-App-secret-dev
    UKM_HOSTNAME: 'ukm.dev'
    UKMresponsive.theme: ''
    UKMresponsive.section:
        title: 'Delta på UKM'
        url: //delta.ukm.dev
    ga_tracking: google api key
    SEOdefaultsApp:
        title: Delta
        canonical: //delta.ukm.dev
        description: 'Meld deg på UKM'
        siteName: 'UKM Delta'
        section: delta