ukm_designbundle:
    resource: "@UKMDesignBundle/Resources/config/routing.yml"
    prefix:   /

ukmapi:
    resource: "@UKMAPIBundle/Resources/config/routing.yml"
    prefix:   /

ukmsms:
    resource: "@UKMSMSBundle/Resources/config/routing.yml"
    prefix:   /

ukm_user:
    resource: "@UKMUserBundle/Resources/config/routing.yml"
    prefix:   /

ukm_delta:
    resource: "@UKMDeltaBundle/Resources/config/routing.yml"
    prefix:   /

ukm_design:
    resource: "@UKMDeltaDesignBundle/Resources/config/routing.yml"
    prefix:   /

ukm_nativeapp:
    resource: "@UKMNAppBundle/Resources/config/routing.yml"
    prefix: /

app:
    resource: @AppBundle/Controller/
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"