services:
    # app.exception_listener:
    #     class: AppBundle\EventListener\ExceptionListener 
    #     arguments: [@service_container]
    #     tags:
    #         - { name: kernel.event_listener, event: kernel.exception }

    fos_user.doctrine_registry:
        alias: doctrine

    twig.extension.debug:
        class: Twig\Extension\DebugExtension
        tags: [{ name: 'twig.extension' }]

    logger:
        alias: 'monolog.logger'
        public: true