<?php

namespace UKMNorge\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * APIKeysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class APIKeysRepository extends EntityRepository
{
}
