<?php

namespace UKMNorge\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DipTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DipTokenRepository extends EntityRepository
{
}
