<?php

namespace UKMNorge\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RequestTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestTokenRepository extends EntityRepository
{
}
