<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerImsSjsQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerImsSjsQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerImsSjsQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerImsSjsQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerImsSjsQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'ImsSjsQ',
    'container.build_id' => 'f75af14b',
    'container.build_time' => 1610366486,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerImsSjsQ');
