<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBu0QECx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBu0QECx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBu0QECx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBu0QECx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBu0QECx\App_KernelDevDebugContainer([
    'container.build_hash' => 'Bu0QECx',
    'container.build_id' => 'eba8c573',
    'container.build_time' => 1610364371,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBu0QECx');
